
[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Allow iframe embedding from fabrom.net
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://fabrom.net https://*.fabrom.net https://fabrom.netlify.app"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=*, microphone=*, geolocation=*, accelerometer=*, gyroscope=*, storage-access=*, clipboard-read=*, clipboard-write=*"

# Environment variables that can be set in the Netlify UI
[build.environment]
  VITE_APP_ENV = "production"
